#!/bin/bash
#PBS -S /bin/sh
#PBS -A wellman_flux
#PBS -q flux
#PBS -l nodes=1:ppn=4,pmem=4000mb,walltime=42:00:00,qos=flux
#PBS -N agr_test_d30f2_cur
#PBS -W group_list=wellman
#PBS -o /home/masondw/att_graph_runner/d30f2out
#PBS -j oe
#PBS -M masondw@umich.edu
#PBS -V
#PBS -m abe
mkdir /tmp/${PBS_JOBID}
mkdir /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/depgraphpy4jattvseither /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/depgraphpy4jdefvseither /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/depgraphpy4jboth /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/dg4jattcli /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/dg4jdefcli /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/dg4jnonetcli /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/graphs /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/simspecs /tmp/${PBS_JOBID}/att_graph_runner
cp /home/masondw/att_graph_runner/*.json /tmp/${PBS_JOBID}/att_graph_runner
cp /home/masondw/att_graph_runner/*d30f2* /tmp/${PBS_JOBID}/att_graph_runner
cp /home/masondw/att_graph_runner/*.py /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/gym /tmp/${PBS_JOBID}
cp -r /home/masondw/baselines /tmp/${PBS_JOBID}
cd /tmp/${PBS_JOBID}/att_graph_runner
python3 master_dq_runner.py 3014 7 d30f2_randNoAndB d30f2 DepgraphJava-v0 \
    DepgraphJavaAtt-v0 DepgraphJavaEnvBoth-v0 RandomGraph30N100E6T1_B.json \
    DepgraphJavaEnvVsMixedDef-v0 DepgraphJavaEnvVsMixedAtt-v0 400 \
    dg_d30f2_dq_mlp_rand_epoch dg_d30f2_dq_mlp_rand_epoch d30 1000000 700000 1 1000 True True
cp /tmp/${PBS_JOBID}/att_graph_runner/*d30f2* /home/masondw/att_graph_runner
rm -rf /tmp/${PBS_JOBID}
