#!/bin/bash
#PBS -S /bin/sh
#PBS -A wellman_flux
#PBS -q flux
#PBS -l nodes=1:ppn=5,pmem=4000mb,walltime=42:00:00,qos=flux
#PBS -N agr_test_d30cf1
#PBS -W group_list=wellman
#PBS -o /home/masondw/att_graph_runner/d30cf1out
#PBS -j oe
#PBS -M masondw@umich.edu
#PBS -V
#PBS -m abe
mkdir /tmp/${PBS_JOBID}
mkdir /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/depgraphpy4jattvseither /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/depgraphpy4jdefvseither /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/depgraphpy4jboth /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/dg4jattcli /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/dg4jdefcli /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/dg4jnonetcli /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/graphs /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/att_graph_runner/simspecs /tmp/${PBS_JOBID}/att_graph_runner
cp /home/masondw/att_graph_runner/*.json /tmp/${PBS_JOBID}/att_graph_runner
cp /home/masondw/att_graph_runner/*d30cf1* /tmp/${PBS_JOBID}/att_graph_runner
cp /home/masondw/att_graph_runner/*.py /tmp/${PBS_JOBID}/att_graph_runner
cp -r /home/masondw/gym /tmp/${PBS_JOBID}
cp -r /home/masondw/baselines /tmp/${PBS_JOBID}
cd /tmp/${PBS_JOBID}/att_graph_runner
python3 master_dq_runner_curve.py 3014 d30cf1_randNoAndB d30cf1 \
    DepgraphJava-v0 DepgraphJavaAtt-v0 DepgraphJavaEnvBoth-v0 RandomGraph30N100E6T1_B.json \
    DepgraphJavaEnvVsMixedDef-v0 DepgraphJavaEnvVsMixedAtt-v0 400 0.7 4 d30 \
    1000000 400000 700000 400000 0 1 500
cp /tmp/${PBS_JOBID}/att_graph_runner/*d30cf1* /home/masondw/att_graph_runner
rm -rf /tmp/${PBS_JOBID}
