from gym.envs.board_game.go import GoEnv
from gym.envs.board_game.hex import HexEnv
from gym.envs.board_game.c4 import C4Env
from gym.envs.board_game.c4_java import C4JavaEnv
from gym.envs.board_game.depgraph_java import DepgraphJavaEnv
from gym.envs.board_game.depgraph_java_conv import DepgraphJavaEnvConv
from gym.envs.board_game.depgraph_java_29N import DepgraphJavaEnv29N
from gym.envs.board_game.depgraph_java_att import DepgraphJavaEnvAtt
from gym.envs.board_game.depgraph_java_att_29N import DepgraphJavaEnvAtt29N
from gym.envs.board_game.dg_java_both import DepgraphJavaEnvBoth
from gym.envs.board_game.dg_java_both_29N import DepgraphJavaEnvBoth29N
from gym.envs.board_game.dg_java_vs_mixed_att import DepgraphJavaEnvVsMixedAtt
from gym.envs.board_game.dg_vs_net_att_test import VsNetworkTest
